load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "remote_eliza_generated",
    url = "https://dl.buf.build/v1/achiu/eliza-java/v1/bufbuild/eliza/dbde79169a014bd8b5bf8f89ac9b35c7.tar.gz",
    build_file = "@//:bufremote.BUILD"
)

local_repository(
    name = "rules_buf",
    path = "../..",
)

load("@rules_buf//buf:repositories.bzl", "rules_buf_dependencies", "rules_buf_toolchains")

rules_buf_dependencies()

rules_buf_toolchains(version = "v1.5.0")

load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")

rules_proto_dependencies()

rules_proto_toolchains()
