load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "remote_eliza_generated",
    # This is going to be dl.<HOST>/v1/{owner_name}/{template_name}/{module_owner_name}/{module_name}/{commit_sha}.tar.gz
    url = "https://dl.buf.build/v1/achiu/eliza-java/v1/bufbuild/eliza/dbde79169a014bd8b5bf8f89ac9b35c7.tar.gz",
    build_file = "@//:remote_eliza.BUILD"
)

# For maven
http_archive(
    name = "rules_jvm_external",
    sha256 = "f36441aa876c4f6427bfb2d1f2d723b48e9d930b62662bf723ddfb8fc80f0140",
    strip_prefix = "rules_jvm_external-4.1",
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/4.1.zip",
)
load("@rules_jvm_external//:defs.bzl", "maven_install")
maven_install(
    artifacts = [
        "io.grpc:grpc-core:1.48.1",
        "io.grpc:grpc-okhttp:1.48.1",
        "com.google.protobuf:protobuf-java:3.19.1",
        "io.grpc:grpc-stub:1.48.1",
        "io.grpc:grpc-api:1.48.1",
        "io.grpc:grpc-all:1.48.1",
        "io.grpc:grpc-protobuf:1.48.1",
    ],
    repositories = [
        "https://maven.google.com",
        "https://repo1.maven.org/maven2",
        "https://jcenter.bintray.com",
    ],
    version_conflict_policy = "pinned",
)

local_repository(
    name = "rules_buf",
    path = "../..",
)

load("@rules_buf//buf:repositories.bzl", "rules_buf_dependencies", "rules_buf_toolchains")

rules_buf_dependencies()

rules_buf_toolchains(version = "v1.5.0")

load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")

rules_proto_dependencies()

rules_proto_toolchains()

